title: AO Razaq 
logo: /me.jpeg
description: Young tech Enthusiast, building a career in Data Science, Analaysis, Machine Learning and AI
Show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
